# Generated by Django 3.2.4 on 2021-06-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendingSystem', '0002_log_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='endDate',
            field=models.DateField(null=True, verbose_name='結束日期'),
        ),
    ]
