# Generated by Django 3.2.4 on 2021-06-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendingSystem', '0003_alter_log_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='endDate',
            field=models.DateField(blank=True, null=True, verbose_name='結束日期'),
        ),
    ]
