# Generated by Django 3.2.4 on 2021-06-17 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dapartment',
            new_name='department',
        ),
    ]
